package ut4_actividadevaluacion;
// Generated 23 ene 2025, 11:29:42 by Hibernate Tools 6.5.1.Final

/**
 * Empleados generated by hbm2java
 */
public class Empleados implements java.io.Serializable {

	private String nif;
	private Oficinas oficinas;
	private String nombre;
	private String direccion;
	private String cargo;

	public Empleados() {
	}

	public Empleados(String nif) {
		this.nif = nif;
	}

	public Empleados(String nif, Oficinas oficinas, String nombre, String direccion, String cargo) {
		this.nif = nif;
		this.oficinas = oficinas;
		this.nombre = nombre;
		this.direccion = direccion;
		this.cargo = cargo;
	}

	public String getNif() {
		return this.nif;
	}

	public void setNif(String nif) {
		this.nif = nif;
	}

	public Oficinas getOficinas() {
		return this.oficinas;
	}

	public void setOficinas(Oficinas oficinas) {
		this.oficinas = oficinas;
	}

	public String getNombre() {
		return this.nombre;
	}

	public void setNombre(String nombre) {
		this.nombre = nombre;
	}

	public String getDireccion() {
		return this.direccion;
	}

	public void setDireccion(String direccion) {
		this.direccion = direccion;
	}

	public String getCargo() {
		return this.cargo;
	}

	public void setCargo(String cargo) {
		this.cargo = cargo;
	}

}
