package ut4_actividadevaluacion;
// Generated 23 ene 2025, 11:29:42 by Hibernate Tools 6.5.1.Final

import java.util.HashSet;
import java.util.Set;

/**
 * Oficinas generated by hbm2java
 */
public class Oficinas implements java.io.Serializable {

	private String codOfi;
	private String nombre;
	private String direccion;
	private String localidad;
	private Set empleadoses = new HashSet(0);

	public Oficinas() {
	}

	public Oficinas(String codOfi) {
		this.codOfi = codOfi;
	}

	public Oficinas(String codOfi, String nombre, String direccion, String localidad, Set empleadoses) {
		this.codOfi = codOfi;
		this.nombre = nombre;
		this.direccion = direccion;
		this.localidad = localidad;
		this.empleadoses = empleadoses;
	}

	public String getCodOfi() {
		return this.codOfi;
	}

	public void setCodOfi(String codOfi) {
		this.codOfi = codOfi;
	}

	public String getNombre() {
		return this.nombre;
	}

	public void setNombre(String nombre) {
		this.nombre = nombre;
	}

	public String getDireccion() {
		return this.direccion;
	}

	public void setDireccion(String direccion) {
		this.direccion = direccion;
	}

	public String getLocalidad() {
		return this.localidad;
	}

	public void setLocalidad(String localidad) {
		this.localidad = localidad;
	}

	public Set getEmpleadoses() {
		return this.empleadoses;
	}

	public void setEmpleadoses(Set empleadoses) {
		this.empleadoses = empleadoses;
	}

}
