package prog;
// Generated 15 ene 2025, 12:51:51 by Hibernate Tools 6.5.1.Final

/**
 * Departamentos generated by hbm2java
 */
public class Departamentos implements java.io.Serializable {

	private int id;
	private String nombre;

	public Departamentos() {
	}

	public Departamentos(int id) {
		this.id = id;
	}

	public Departamentos(int id, String nombre) {
		this.id = id;
		this.nombre = nombre;
	}

	public int getId() {
		return this.id;
	}

	public void setId(int id) {
		this.id = id;
	}

	public String getNombre() {
		return this.nombre;
	}

	public void setNombre(String nombre) {
		this.nombre = nombre;
	}

}
