package ORACLE;
// Generated 28 ene 2025, 21:18:08 by Hibernate Tools 5.4.33.Final

/**
 * Empleados generated by hbm2java
 */
public class Empleados implements java.io.Serializable {

	private String nif;
	private Oficinas oficinas;
	private String nombre;
	private String dirección;
	private String cargo;

	public Empleados() {
	}

	public Empleados(String nif) {
		this.nif = nif;
	}

	public Empleados(String nif, Oficinas oficinas, String nombre, String dirección, String cargo) {
		this.nif = nif;
		this.oficinas = oficinas;
		this.nombre = nombre;
		this.dirección = dirección;
		this.cargo = cargo;
	}

	public String getNif() {
		return this.nif;
	}

	public void setNif(String nif) {
		this.nif = nif;
	}

	public Oficinas getOficinas() {
		return this.oficinas;
	}

	public void setOficinas(Oficinas oficinas) {
		this.oficinas = oficinas;
	}

	public String getNombre() {
		return this.nombre;
	}

	public void setNombre(String nombre) {
		this.nombre = nombre;
	}

	public String getDirección() {
		return this.dirección;
	}

	public void setDirección(String dirección) {
		this.dirección = dirección;
	}

	public String getCargo() {
		return this.cargo;
	}

	public void setCargo(String cargo) {
		this.cargo = cargo;
	}

}
