package ORACLE;
// Generated 28 ene 2025, 21:18:08 by Hibernate Tools 5.4.33.Final

import java.util.HashSet;
import java.util.Set;

/**
 * Oficinas generated by hbm2java
 */
public class Oficinas implements java.io.Serializable {

	private String codOfi;
	private String nombre;
	private String dirección;
	private String localidad;
	private Set empleadoses = new HashSet(0);

	public Oficinas() {
	}

	public Oficinas(String codOfi) {
		this.codOfi = codOfi;
	}

	public Oficinas(String codOfi, String nombre, String dirección, String localidad, Set empleadoses) {
		this.codOfi = codOfi;
		this.nombre = nombre;
		this.dirección = dirección;
		this.localidad = localidad;
		this.empleadoses = empleadoses;
	}

	public String getCodOfi() {
		return this.codOfi;
	}

	public void setCodOfi(String codOfi) {
		this.codOfi = codOfi;
	}

	public String getNombre() {
		return this.nombre;
	}

	public void setNombre(String nombre) {
		this.nombre = nombre;
	}

	public String getDirección() {
		return this.dirección;
	}

	public void setDirección(String dirección) {
		this.dirección = dirección;
	}

	public String getLocalidad() {
		return this.localidad;
	}

	public void setLocalidad(String localidad) {
		this.localidad = localidad;
	}

	public Set getEmpleadoses() {
		return this.empleadoses;
	}

	public void setEmpleadoses(Set empleadoses) {
		this.empleadoses = empleadoses;
	}

}
