package ut2_act_evaluacion;
// Generated 8 ene 2025, 10:12:45 by Hibernate Tools 6.5.1.Final

/**
 * PedidosPendientes generated by hbm2java
 */
public class PedidosPendientes implements java.io.Serializable {

	private PedidosPendientesId id;
	private Proveedores proveedores;

	public PedidosPendientes() {
	}

	public PedidosPendientes(PedidosPendientesId id) {
		this.id = id;
	}

	public PedidosPendientes(PedidosPendientesId id, Proveedores proveedores) {
		this.id = id;
		this.proveedores = proveedores;
	}

	public PedidosPendientesId getId() {
		return this.id;
	}

	public void setId(PedidosPendientesId id) {
		this.id = id;
	}

	public Proveedores getProveedores() {
		return this.proveedores;
	}

	public void setProveedores(Proveedores proveedores) {
		this.proveedores = proveedores;
	}

}
