package ut2_act_evaluacion;
// Generated 8 ene 2025, 10:12:45 by Hibernate Tools 6.5.1.Final

import java.sql.Date;

/**
 * PedidosPendientesId generated by hbm2java
 */
public class PedidosPendientesId implements java.io.Serializable {

	private String codProv;
	private Date fechaModificacion;
	private Integer stock;

	public PedidosPendientesId() {
	}

	public PedidosPendientesId(String codProv, Date fechaModificacion, Integer stock) {
		this.codProv = codProv;
		this.fechaModificacion = fechaModificacion;
		this.stock = stock;
	}

	public String getCodProv() {
		return this.codProv;
	}

	public void setCodProv(String codProv) {
		this.codProv = codProv;
	}

	public Date getFechaModificacion() {
		return this.fechaModificacion;
	}

	public void setFechaModificacion(Date fechaModificacion) {
		this.fechaModificacion = fechaModificacion;
	}

	public Integer getStock() {
		return this.stock;
	}

	public void setStock(Integer stock) {
		this.stock = stock;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof PedidosPendientesId))
			return false;
		PedidosPendientesId castOther = (PedidosPendientesId) other;

		return ((this.getCodProv() == castOther.getCodProv()) || (this.getCodProv() != null
				&& castOther.getCodProv() != null && this.getCodProv().equals(castOther.getCodProv())))
				&& ((this.getFechaModificacion() == castOther.getFechaModificacion())
						|| (this.getFechaModificacion() != null && castOther.getFechaModificacion() != null
								&& this.getFechaModificacion().equals(castOther.getFechaModificacion())))
				&& ((this.getStock() == castOther.getStock()) || (this.getStock() != null
						&& castOther.getStock() != null && this.getStock().equals(castOther.getStock())));
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result + (getCodProv() == null ? 0 : this.getCodProv().hashCode());
		result = 37 * result + (getFechaModificacion() == null ? 0 : this.getFechaModificacion().hashCode());
		result = 37 * result + (getStock() == null ? 0 : this.getStock().hashCode());
		return result;
	}

}
