package ut2_act_evaluacion;
// Generated 8 ene 2025, 10:12:45 by Hibernate Tools 6.5.1.Final

/**
 * Productos generated by hbm2java
 */
public class Productos implements java.io.Serializable {

	private String codProd;
	private Proveedores proveedores;
	private String nombreProd;
	private Double precio;
	private Integer stock;

	public Productos() {
	}

	public Productos(String codProd) {
		this.codProd = codProd;
	}

	public Productos(String codProd, Proveedores proveedores, String nombreProd, Double precio, Integer stock) {
		this.codProd = codProd;
		this.proveedores = proveedores;
		this.nombreProd = nombreProd;
		this.precio = precio;
		this.stock = stock;
	}

	public String getCodProd() {
		return this.codProd;
	}

	public void setCodProd(String codProd) {
		this.codProd = codProd;
	}

	public Proveedores getProveedores() {
		return this.proveedores;
	}

	public void setProveedores(Proveedores proveedores) {
		this.proveedores = proveedores;
	}

	public String getNombreProd() {
		return this.nombreProd;
	}

	public void setNombreProd(String nombreProd) {
		this.nombreProd = nombreProd;
	}

	public Double getPrecio() {
		return this.precio;
	}

	public void setPrecio(Double precio) {
		this.precio = precio;
	}

	public Integer getStock() {
		return this.stock;
	}

	public void setStock(Integer stock) {
		this.stock = stock;
	}

}
