package ut2_act_evaluacion;
// Generated 8 ene 2025, 10:12:45 by Hibernate Tools 6.5.1.Final

import java.util.HashSet;
import java.util.Set;

/**
 * Proveedores generated by hbm2java
 */
public class Proveedores implements java.io.Serializable {

	private String codProv;
	private String nombreProv;
	private String direccion;
	private String telefono;
	private Double bonifica;
	private Set pedidosPendienteses = new HashSet(0);
	private Set productoses = new HashSet(0);

	public Proveedores() {
	}

	public Proveedores(String codProv) {
		this.codProv = codProv;
	}

	public Proveedores(String codProv, String nombreProv, String direccion, String telefono, Double bonifica,
			Set pedidosPendienteses, Set productoses) {
		this.codProv = codProv;
		this.nombreProv = nombreProv;
		this.direccion = direccion;
		this.telefono = telefono;
		this.bonifica = bonifica;
		this.pedidosPendienteses = pedidosPendienteses;
		this.productoses = productoses;
	}

	public String getCodProv() {
		return this.codProv;
	}

	public void setCodProv(String codProv) {
		this.codProv = codProv;
	}

	public String getNombreProv() {
		return this.nombreProv;
	}

	public void setNombreProv(String nombreProv) {
		this.nombreProv = nombreProv;
	}

	public String getDireccion() {
		return this.direccion;
	}

	public void setDireccion(String direccion) {
		this.direccion = direccion;
	}

	public String getTelefono() {
		return this.telefono;
	}

	public void setTelefono(String telefono) {
		this.telefono = telefono;
	}

	public Double getBonifica() {
		return this.bonifica;
	}

	public void setBonifica(Double bonifica) {
		this.bonifica = bonifica;
	}

	public Set getPedidosPendienteses() {
		return this.pedidosPendienteses;
	}

	public void setPedidosPendienteses(Set pedidosPendienteses) {
		this.pedidosPendienteses = pedidosPendienteses;
	}

	public Set getProductoses() {
		return this.productoses;
	}

	public void setProductoses(Set productoses) {
		this.productoses = productoses;
	}

}
