package ut4_actividad3;
// Generated 15 ene 2025, 23:31:35 by Hibernate Tools 6.5.1.Final

import java.util.HashSet;
import java.util.Set;

/**
 * Departamentos generated by hbm2java
 */
public class Departamentos implements java.io.Serializable {

	private int deptno;
	private String nombre;
	private String localidad;
	private Set empleadoses = new HashSet(0);

	public Departamentos() {
	}

	public Departamentos(int deptno) {
		this.deptno = deptno;
	}

	public Departamentos(int deptno, String nombre, String localidad, Set empleadoses) {
		this.deptno = deptno;
		this.nombre = nombre;
		this.localidad = localidad;
		this.empleadoses = empleadoses;
	}

	public int getDeptno() {
		return this.deptno;
	}

	public void setDeptno(int deptno) {
		this.deptno = deptno;
	}

	public String getNombre() {
		return this.nombre;
	}

	public void setNombre(String nombre) {
		this.nombre = nombre;
	}

	public String getLocalidad() {
		return this.localidad;
	}

	public void setLocalidad(String localidad) {
		this.localidad = localidad;
	}

	public Set getEmpleadoses() {
		return this.empleadoses;
	}

	public void setEmpleadoses(Set empleadoses) {
		this.empleadoses = empleadoses;
	}

}
