package ut4_actividad3;
// Generated 15 ene 2025, 23:31:35 by Hibernate Tools 6.5.1.Final

/**
 * Empleados generated by hbm2java
 */
public class Empleados implements java.io.Serializable {

	private EmpleadosId id;
	private Departamentos departamentos;

	public Empleados() {
	}

	public Empleados(EmpleadosId id) {
		this.id = id;
	}

	public Empleados(EmpleadosId id, Departamentos departamentos) {
		this.id = id;
		this.departamentos = departamentos;
	}

	public EmpleadosId getId() {
		return this.id;
	}

	public void setId(EmpleadosId id) {
		this.id = id;
	}

	public Departamentos getDepartamentos() {
		return this.departamentos;
	}

	public void setDepartamentos(Departamentos departamentos) {
		this.departamentos = departamentos;
	}

}
