package ut4_actividad3;
// Generated 15 ene 2025, 23:31:35 by Hibernate Tools 6.5.1.Final

/**
 * EmpleadosId generated by hbm2java
 */
public class EmpleadosId implements java.io.Serializable {

	private String cargo;
	private Integer deptno;
	private String ofi;
	private Double salario;

	public EmpleadosId() {
	}

	public EmpleadosId(String cargo, Integer deptno, String ofi, Double salario) {
		this.cargo = cargo;
		this.deptno = deptno;
		this.ofi = ofi;
		this.salario = salario;
	}

	public String getCargo() {
		return this.cargo;
	}

	public void setCargo(String cargo) {
		this.cargo = cargo;
	}

	public Integer getDeptno() {
		return this.deptno;
	}

	public void setDeptno(Integer deptno) {
		this.deptno = deptno;
	}

	public String getOfi() {
		return this.ofi;
	}

	public void setOfi(String ofi) {
		this.ofi = ofi;
	}

	public Double getSalario() {
		return this.salario;
	}

	public void setSalario(Double salario) {
		this.salario = salario;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof EmpleadosId))
			return false;
		EmpleadosId castOther = (EmpleadosId) other;

		return ((this.getCargo() == castOther.getCargo()) || (this.getCargo() != null && castOther.getCargo() != null
				&& this.getCargo().equals(castOther.getCargo())))
				&& ((this.getDeptno() == castOther.getDeptno()) || (this.getDeptno() != null
						&& castOther.getDeptno() != null && this.getDeptno().equals(castOther.getDeptno())))
				&& ((this.getOfi() == castOther.getOfi()) || (this.getOfi() != null && castOther.getOfi() != null
						&& this.getOfi().equals(castOther.getOfi())))
				&& ((this.getSalario() == castOther.getSalario()) || (this.getSalario() != null
						&& castOther.getSalario() != null && this.getSalario().equals(castOther.getSalario())));
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result + (getCargo() == null ? 0 : this.getCargo().hashCode());
		result = 37 * result + (getDeptno() == null ? 0 : this.getDeptno().hashCode());
		result = 37 * result + (getOfi() == null ? 0 : this.getOfi().hashCode());
		result = 37 * result + (getSalario() == null ? 0 : this.getSalario().hashCode());
		return result;
	}

}
