package ut4_actividadevaluacion;
// Generated 23 ene 2025, 11:25:59 by Hibernate Tools 6.5.1.Final

/**
 * Departamentos generated by hbm2java
 */
public class Departamentos implements java.io.Serializable {

	private int deptno;
	private String nombre;
	private String localidad;

	public Departamentos() {
	}

	public Departamentos(int deptno) {
		this.deptno = deptno;
	}

	public Departamentos(int deptno, String nombre, String localidad) {
		this.deptno = deptno;
		this.nombre = nombre;
		this.localidad = localidad;
	}

	public int getDeptno() {
		return this.deptno;
	}

	public void setDeptno(int deptno) {
		this.deptno = deptno;
	}

	public String getNombre() {
		return this.nombre;
	}

	public void setNombre(String nombre) {
		this.nombre = nombre;
	}

	public String getLocalidad() {
		return this.localidad;
	}

	public void setLocalidad(String localidad) {
		this.localidad = localidad;
	}

}
